---
title: "Template APG"
author: "Riofebri Prasetia"
date: '2022-03-30'
output: html_document
---

Nomor 1

#load library
```{r}
library(openxlsx)
library(car)
library(MVN)
```

```{r}
url1 <- "https://raw.githubusercontent.com/rii92/tugas-APG/main/KuisPertemuan7/Kuis2_data.csv"
essay <- read.csv(url1)
essay
```

a.

H0: miu1 - miu2 = 0
H1: miu1 - miu2 != 0

```{r}
dWords <- essay[, 1] - essay[, 3]
dVerbs <- essay[, 2] - essay[, 4]
dessay <- cbind(dWords, dVerbs)
dessay
```

```{r}
dbaressay <- colMeans(dessay)
dbaressay
```

```{r}
Sessay <- cov(dessay)
Sessay
```

```{r}
T2 <- t(dbaressay) %*% solve(Sessay) %*% (dbaressay)
T2
```


```{r}
pessay <- 2
nessay <- nrow(dessay)
alphaessay = 0.05

C2 <- (((nessay - 1) * pessay)/((nessay - pessay) * nessay)) * qf(p = 1 - alphaessay, df1 = pessay, df2 = nessay - pessay)

C2
```

-> Tolak H0
b. 
##Membuat Ellipse
```{r}
mu <- c(0,0)
X <- dessay
n <- nrow(X)
p <- ncol(X)
xbar <- colMeans(X)
S <- cov(X)
library(car)
alpha<-alphaessay
tconst <- sqrt((p/n)*((n-1)/(n-p)) *
                 qf(1-alpha,p,n-p))
id <- c(1,2)
plot(ellipse(center=xbar[id], shape=S[id,id],
             radius=tconst, draw=F),type="n", xlab = "d1", ylab = "d2", xlim = c(-56.4,0.25))
lines(ellipse(center=xbar[id], shape=S[id,id],
              radius=tconst, lwd=3))
points(mu[1],mu[2],col="red", pch=16)
text(mu[1]+1.5,mu[2],expression(d[0]))
text(xbar[1]+1.5,xbar[2],expression(bar(d)))
```

c.

```{r}
bon <- NULL 
alpha3 <- 1 - (0.05/(2*p))

for(k in 1:2){
  bon <- c(bon, dbaressay[k] - sqrt(S[k,k]/n) * qt(alpha3, df=n-1), dbaressay[k] + sqrt(S[k,k]/n) * qt(alpha3, df=n-1))
}

rtab <- rbind(bon)
round(rtab, 2)
```


Nomor 2

a.
H0: miu1 - miu2 = 0
H1: miu1 - miu2 != 0

b.

```{r}
#load data
url2 <- "https://raw.githubusercontent.com/rii92/tugas-APG/main/KuisPertemuan7/testIq.csv"
Iq <- read.csv(url2)
Iq
```

```{r}
grupC <- Iq[c(1:9), c("Baca", "Hitung", "IQ")]
grupT <- Iq[c(10:18), c("Baca", "Hitung", "IQ")]
print(paste("data group C"))
grupC
print(paste("data group T"))
grupT
```

```{r}
xbargrupC <- colMeans(grupC)
xbargrupC
xbargrupT <- colMeans(grupT)
xbargrupT
```

```{r}
SgrupC <- cov(grupC)
SgrupT <- cov(grupT)
print(paste("kovarians group C"))
SgrupC
print(paste("kovarians group T"))
SgrupT
```

```{r}
ngrupC <- nrow(grupC)
ngrupT <- nrow(grupT)

Spooled <- (1/(ngrupC + ngrupT - 2)) * (((ngrupC - 1) * SgrupC) + ((ngrupT - 1) * SgrupT))
Spooled
```

```{r}
T2_grup <- t(xbargrupC - xbargrupT) %*% solve(((1/ngrupC) + (1/ngrupT)) * Spooled) %*% (xbargrupC - xbargrupT)
T2_grup
```

```{r}
pgrup <- 3
alphagrup <- 0.05

C2_grup <- (((ngrupC + ngrupT - 2) * pgrup)/(ngrupC + ngrupT - pgrup - 1)) * qf(p = 1-alphagrup, df1 = pgrup, df2 = ngrupC + ngrupT - pgrup - 1)

C2_grup
```


c.

```{r}
bon_grup <- NULL
alpha_bon <- (0.05/(2 * pgrup))

for (k in c(1:3)) {
  bon_grup <- c(bon_grup, (xbargrupC[k] - xbargrupT[k]) - qt(p = 1-alpha_bon, df = ngrupC + ngrupT - 2) * sqrt(((1/ngrupC) + (1/ngrupT)) * Spooled[k,k]), (xbargrupC[k] - xbargrupT[k]) + qt(p = 1-alpha_bon, df = ngrupC + ngrupT - 2) * sqrt(((1/ngrupC) + (1/ngrupT)) * Spooled[k,k]))
}

rtab <- rbind(bon_grup)
round(rtab, 3)
```


d.
i. Grup C

```{r}
set.seed(1000)
mvn(grupC, mvnTest = "mardia")
```

ii. Grup T

```{r}
mvn(grupT, mvnTest = "mardia")
```

iii. semua
```{r}
mvn(Iq[, c("Baca", "Hitung", "IQ")], mvnTest = "mardia")
```